version: '3.8'

services:
  trackyourhealth-api:
    image: node:16-alpine3.14
    volumes:
      - .:/app
    working_dir: /app
    command: npx nx serve api

  trackyourhealth-db:
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER:-pgadmin@local.host}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pgadmin}
