version: '3.8'

networks:
  trackyourhealth:

services:
  trackyourhealth-api:
    container_name: trackyourhealth-api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - trackyourhealth-db
    networks:
      - trackyourhealth

  trackyourhealth-db:
    container_name: trackyourhealth-db
    image: postgres:14.2-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - trackyourhealth

  pgadmin:
    container_name: trackyourhealth-pgadmin
    image: dpage/pgadmin4:6.7
    depends_on:
      - trackyourhealth-db
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - trackyourhealth

volumes:
  data-trackyourhealth-db:
