version: '3.8'

networks:
  trackyourhealth:

services:
  trackyourhealth-api:
    container_name: trackyourhealth-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - trackyourhealth-db
    env_file:
      - .env
    networks:
      - trackyourhealth

  trackyourhealth-db:
    container_name: trackyourhealth-db
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - data-trackyourhealth-db:/var/lib/postgresql/data
    networks:
      - trackyourhealth

  pgadmin:
    container_name: trackyourhealth-pgadmin
    image: dpage/pgadmin4:6.7
    depends_on:
      - trackyourhealth-db
    ports:
      - ${PGA_PORT}:80
    networks:
      - trackyourhealth

volumes:
  data-trackyourhealth-db:
